/**
 * Client-side PDF report generation for Emotion AI
 * Uses jsPDF for lightweight, no-server PDF creation
 */
import { jsPDF } from 'jspdf';
import {
  EXPRESSION_LABELS,
  EMOJI_MAP,
  formatDuration,
  calculateExpressionScore,
  getCategoryBreakdown,
  generateInsights,
} from './expressionUtils';

/**
 * Generate a PDF report from session data
 */
export function generatePDFReport(session) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Title
  doc.setFontSize(22);
  doc.setTextColor(99, 102, 241);
  doc.text('EMOTION AI', pageWidth / 2, y, { align: 'center' });
  y += 8;

  doc.setFontSize(10);
  doc.setTextColor(148, 163, 184);
  doc.text('Session Analysis Report', pageWidth / 2, y, { align: 'center' });
  y += 16;

  // Divider
  doc.setDrawColor(99, 102, 241);
  doc.setLineWidth(0.5);
  doc.line(20, y, pageWidth - 20, y);
  y += 12;

  // Session Info
  doc.setFontSize(12);
  doc.setTextColor(30, 30, 30);
  doc.text('Session Overview', 20, y);
  y += 8;

  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);

  const date = new Date(session.startTime);
  const infoLines = [
    `Date: ${date.toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}`,
    `Time: ${date.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: true })}`,
    `Duration: ${formatDuration(session.durationSeconds)}`,
    `Total Detections: ${session.totalDetections}`,
    `Average Confidence: ${Math.round((session.averageConfidence || 0) * 100)}%`,
  ];

  for (const line of infoLines) {
    doc.text(line, 25, y);
    y += 6;
  }
  y += 8;

  // Expression Score
  const score = calculateExpressionScore(session.distribution);
  doc.setFontSize(12);
  doc.setTextColor(30, 30, 30);
  doc.text('Expression Score', 20, y);
  y += 8;

  doc.setFontSize(24);
  doc.setTextColor(99, 102, 241);
  doc.text(`${score} / 100`, 25, y);
  y += 6;

  const categories = getCategoryBreakdown(session.distribution);
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text(`Positive: ${categories.positive}%  |  Neutral: ${categories.neutral}%  |  Negative: ${categories.negative}%`, 25, y);
  y += 14;

  // Expression Distribution
  doc.setFontSize(12);
  doc.setTextColor(30, 30, 30);
  doc.text('Expression Distribution', 20, y);
  y += 8;

  const total = Object.values(session.distribution || {}).reduce((s, v) => s + v, 0);
  const sorted = Object.entries(session.distribution || {})
    .sort((a, b) => b[1] - a[1]);

  doc.setFontSize(10);
  for (const [expr, count] of sorted) {
    const pct = total > 0 ? Math.round((count / total) * 100) : 0;
    const label = EXPRESSION_LABELS[expr] || expr;
    doc.setTextColor(80, 80, 80);
    doc.text(`${label}`, 25, y);
    doc.setTextColor(99, 102, 241);
    doc.text(`${pct}%`, 90, y);

    // Progress bar
    doc.setFillColor(230, 230, 240);
    doc.roundedRect(110, y - 3.5, 70, 5, 2, 2, 'F');
    if (pct > 0) {
      doc.setFillColor(99, 102, 241);
      doc.roundedRect(110, y - 3.5, (pct / 100) * 70, 5, 2, 2, 'F');
    }
    y += 8;
  }
  y += 8;

  // Key Insights
  const insights = generateInsights(session);
  if (insights.length > 0) {
    doc.setFontSize(12);
    doc.setTextColor(30, 30, 30);
    doc.text('Key Insights', 20, y);
    y += 8;

    doc.setFontSize(9);
    doc.setTextColor(80, 80, 80);
    for (const insight of insights) {
      const lines = doc.splitTextToSize(`• ${insight}`, pageWidth - 50);
      for (const line of lines) {
        if (y > 275) {
          doc.addPage();
          y = 20;
        }
        doc.text(line, 25, y);
        y += 5;
      }
      y += 2;
    }
  }

  // Footer
  y = 285;
  doc.setDrawColor(200, 200, 210);
  doc.setLineWidth(0.3);
  doc.line(20, y - 5, pageWidth - 20, y - 5);
  doc.setFontSize(8);
  doc.setTextColor(160, 160, 170);
  doc.text('Generated by Emotion AI — Facial Expression Intelligence Platform', pageWidth / 2, y, { align: 'center' });
  doc.text('Expression data is based on detected facial patterns, not psychological assessment.', pageWidth / 2, y + 4, { align: 'center' });

  // Save
  const filename = `emotionai-report-${date.toISOString().split('T')[0]}.pdf`;
  doc.save(filename);
}
